//
//  FinanceScreenViewController.swift
//  SantanderTest
//
//  Created by Marcos Barbosa on 09/04/19.
//  Copyright (c) 2019 Marcos Barbosa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FinanceScreenDisplayLogic: class {
    func displayFinance(viewModel: FinanceScreen.Data.ViewModel)
    func showErrorMessage()
}

class FinanceScreenViewController: UIViewController, FinanceScreenDisplayLogic {
    var interactor: FinanceScreenBusinessLogic?
    var router: (NSObjectProtocol & FinanceScreenRoutingLogic & FinanceScreenDataPassing)?
    
    @IBOutlet weak var titleLabel: UILabel!
    @IBOutlet weak var fundNameLabel: UILabel!
    @IBOutlet weak var buttonInvestiment: UIButton!
    
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = FinanceScreenInteractor()
        let presenter = FinanceScreenPresenter()
        let router = FinanceScreenRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        print("finance init")
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething() {
        let request = FinanceScreen.Data.Request.init(url: URLS.FinanceActive.rawValue)
        interactor?.requestFinances(request: request)
    }
    
    func displayFinance(viewModel: FinanceScreen.Data.ViewModel) {
        //nameTextField.text = viewModel.name
        self.titleLabel.text = viewModel.data.screen?.title
        self.fundNameLabel.text = viewModel.data.screen?.fundName
        self.buttonInvestiment.layer.cornerRadius = self.buttonInvestiment.frame.height/2
    }
    
    func showErrorMessage() {
        
    }
}
