//
//  FinanceScreenPresenter.swift
//  SantanderTest
//
//  Created by Marcos Barbosa on 09/04/19.
//  Copyright (c) 2019 Marcos Barbosa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FinanceScreenPresentationLogic {
    func presentFinance(response: FinanceScreen.Data.Response)
}

class FinanceScreenPresenter: FinanceScreenPresentationLogic {
    weak var viewController: FinanceScreenDisplayLogic?
    
    // MARK: Do something
    
    func presentFinance(response: FinanceScreen.Data.Response) {
        
        if response.isError {
            viewController?.showErrorMessage()
        } else {
            if let result: FinanceModel = response.data {
                let viewModel = FinanceScreen.Data.ViewModel.init(data: result)
                viewController?.displayFinance(viewModel: viewModel)
            }
        }
    }
}
