//
//  FinanceScreenViewController.swift
//  SantanderTest
//
//  Created by Marcos Barbosa on 09/04/19.
//  Copyright (c) 2019 Marcos Barbosa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FinanceScreenDisplayLogic: class {
    func displayFinance(viewModel: FinanceScreen.Data.ViewModel)
    func showErrorMessage()
}

class FinanceScreenViewController: UIViewController, FinanceScreenDisplayLogic {
    var interactor: FinanceScreenBusinessLogic?
    var router: (NSObjectProtocol & FinanceScreenRoutingLogic & FinanceScreenDataPassing)?
    
    @IBOutlet weak var titleLabel: UILabel!
    @IBOutlet weak var fundNameLabel: UILabel!
    @IBOutlet weak var buttonInvestiment: UIButton!
    @IBOutlet weak var whatISLabel: UILabel!
    @IBOutlet weak var definitionLabel: UILabel!
    @IBOutlet weak var riskTitleLabel: UILabel!
    @IBOutlet weak var infoTitleLabel: UILabel!
    
    
    @IBOutlet weak var riskOneHeight: NSLayoutConstraint!
    @IBOutlet weak var riskTwoHeight: NSLayoutConstraint!
    @IBOutlet weak var riskThreeHeight: NSLayoutConstraint!
    @IBOutlet weak var riskFourHeight: NSLayoutConstraint!
    @IBOutlet weak var riskFiveHeight: NSLayoutConstraint!
    
    @IBOutlet weak var riskOneArrow: UIImageView!
    @IBOutlet weak var riskTwoArrow: UIImageView!
    @IBOutlet weak var riskThreeArrow: UIImageView!
    @IBOutlet weak var riskFourArrow: UIImageView!
    @IBOutlet weak var riskFiveArrow: UIImageView!
    
    
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = FinanceScreenInteractor()
        let presenter = FinanceScreenPresenter()
        let router = FinanceScreenRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        doSomething()
        configureRisk(risk: nil)
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        print("finance init")
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething() {
        let request = FinanceScreen.Data.Request.init(url: URLS.FinanceActive.rawValue)
        interactor?.requestFinances(request: request)
    }
    
    func displayFinance(viewModel: FinanceScreen.Data.ViewModel) {
        //nameTextField.text = viewModel.name
        self.titleLabel.text = viewModel.data.screen?.title
        self.fundNameLabel.text = viewModel.data.screen?.fundName
        self.whatISLabel.text = viewModel.data.screen?.whatIs
        self.definitionLabel.text = viewModel.data.screen?.definition
        self.riskTitleLabel.text = viewModel.data.screen?.riskTitle
        self.configureRisk(risk: viewModel.data.screen?.risk)
        self.infoTitleLabel.text = viewModel.data.screen?.infoTitle
        
        self.buttonInvestiment.layer.cornerRadius = self.buttonInvestiment.frame.height/2
    }
    
    func showErrorMessage() {
        
    }
    
    func configureRisk(risk: Int?) {
        
        self.riskOneArrow.isHidden = true
        self.riskTwoArrow.isHidden = true
        self.riskThreeArrow.isHidden = true
        self.riskFourArrow.isHidden = true
        self.riskFiveArrow.isHidden = true
        
        self.riskOneHeight.constant = 5
        self.riskTwoHeight.constant = 5
        self.riskThreeHeight.constant = 5
        self.riskFourHeight.constant = 5
        self.riskFiveHeight.constant = 5
        
        if let _risk = risk {
            
            switch _risk {
                
            case 1:
                self.riskOneArrow.isHidden = false
                self.riskOneHeight.constant = 10
                
            case 2:
                self.riskTwoArrow.isHidden = false
                self.riskTwoHeight.constant = 10
                
            case 3:
                self.riskThreeArrow.isHidden = false
                self.riskThreeHeight.constant = 10
                
            case 4:
                self.riskFourArrow.isHidden = false
                self.riskFourHeight.constant = 10
                
            case 5:
                self.riskFiveArrow.isHidden = false
                self.riskFiveHeight.constant = 10
                
            default:
                break
                
            }
            
        }
    }
}
