//
//  FinanceScreenModels.swift
//  SantanderTest
//
//  Created by Marcos Barbosa on 09/04/19.
//  Copyright (c) 2019 Marcos Barbosa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum FinanceScreen {
    // MARK: Use cases
    
    enum Data {
        struct Request {
            var url: String
        }
        
        struct Response {
            var isError: Bool
            var data: FinanceModel?
        }
        
        struct ViewModel {
            var data: FinanceModel
        }
    }
}
