//
//  FormScreenModels.swift
//  SantanderTest
//
//  Created by Marcos Barbosa on 08/04/19.
//  Copyright (c) 2019 Marcos Barbosa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum FormScreen {
  // MARK: Use cases
  
  enum Data {
    struct Request {
        var url: String
    }
    struct Response {
        var isError: Bool
        var data: FormsModel?
    }
    struct ViewModel {
        var id: Int
        var type: Int?
        var message: String?
        var typefield: Any?
        var hidden: Bool?
        var topSpacing: Double?
        var show: String?
        var required: Bool?
    }
  }
}

